FROM confluentinc/cp-kafka-connect:7.5.0

USER root
RUN microdnf update && microdnf install -y unzip && microdnf clean all

# Azure만 Aiven ZIP으로 수동 설치 (라이선스 에러 회피용)
COPY aiven-azure-blob.zip /tmp/
RUN mkdir -p /usr/share/confluent-hub-components/azure-blob-aiven/lib && \
    unzip -o -j /tmp/aiven-azure-blob.zip "*/lib/*.jar" -d /usr/share/confluent-hub-components/azure-blob-aiven/lib/

RUN chown -R appuser:appuser /usr/share/confluent-hub-components && rm /tmp/*.zip

USER appuser